---
# tasks file for ansible-rsyslog
- name: "Run installer tasks for Debian"
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: "Run installer tasks for Debian"
  import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Flush handlers
  meta: flush_handlers
