---
- name: Installation Tasks
  tags:
    - rsyslog-install
  block:
    - name: Wait for locks
      ansible.builtin.include_tasks:
        file: wait_for_locks.yml
        apply:
          tags:
            - rsyslog-install

    - name: Install rsyslog
      ansible.builtin.package:
        name: rsyslog
        state: present
      register: result
      until: result is successful

- name: Configuration Tasks
  tags:
    - rsyslog-configure
  block:
    - name: Configuring rsyslog.conf
      ansible.builtin.template:
        src: etc/rsyslog.conf.j2
        dest: "{{ rsyslog_config_file }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - restart rsyslog
      when:
        - rsyslog_config is defined
        - rsyslog_config|bool

    - name: Configuring rsyslog rules
      ansible.builtin.template:
        src: etc/rsyslog.d/50-default.conf.j2
        dest: "{{ rsyslog_default_rules_file }}"
        owner: root
        group: root
        mode: "0644"
      notify:
        - restart rsyslog
      when:
        - rsyslog_config is defined
        - rsyslog_config|bool
